version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run lint
      - npm run jest
  build:
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t sushiro-hk-waiting:latest .
artifacts:
  files:
    - '**/*'